name: laravel-app

services:
  - name: web
    environment_slug: php
    build_command: chmod +x build.sh && ./build.sh
    run_command: chmod +x deploy.sh && ./deploy.sh && heroku-php-apache2 public/
